language: rust
sudo: false

cache: cargo

os:
  - linux
  - osx

rust:
  - 1.15.0
  - stable
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
  - cargo test --no-default-features
